/* eslint-disable */
export const LOAD_ALL_TWITS = 'LOAD_ALL_TWITS';
export const LOAD_ALL_TWITS_SUCCESS = 'LOAD_ALL_TWITS_SUCCESS';
export const LOAD_ALL_TWITS_FAILURE = 'LOAD_ALL_TWITS_FAILURE';
export const SUBMIT_NEW_TWEET = 'SUBMIT_NEW_TWEET';
export const SUBMIT_NEW_COMMENT = 'SUBMIT_NEW_COMMENT';
export const HANDLE_CHANGE_ON_TWIT_FIELD = 'HANDLE_CHANGE_ON_TWIT_FIELD';
export const HANDLE_CHANGE_ON_FIELD = 'HANDLE_CHANGE_ON_FIELD';
